/**
 * Architecture.
 *
 * The pipeline from physical asset to maintenance decision, with each stage
 * honestly labelled as implemented, simulated, or modelled-but-not-present. A
 * reviewer should be able to tell in one pass which parts of an industrial
 * monitoring chain this project actually builds and which it stands in for.
 */

import { ArrowDown, ArrowRight } from 'lucide-react'
import { Card, PageHeading, ProvenanceNote, StatusBadge } from '../components/ui'
import { PUMP } from '../lib/pumpPhysics'
import type { Tone } from '../lib/status'

interface Stage {
  name: string
  role: string
  detail: string
  status: { tone: Tone; label: string; detail: string }
}

const SIMULATED = {
  tone: 'warn' as Tone,
  label: 'SIMULATED',
  detail: 'Stood in for by software; no hardware exists',
}
const IMPLEMENTED = {
  tone: 'ok' as Tone,
  label: 'IMPLEMENTED',
  detail: 'Real code in this project',
}
/**
 * For a stage whose LOGIC is implemented but whose PLATFORM is not the one the
 * stage is named after. The PLC row earned this: the state machine and the
 * interlocks are real, tested code, but they are Python, and a plain
 * IMPLEMENTED next to the word "PLC" invites a reader to assume ladder logic on
 * industrial hardware. That is a small overclaim, and small overclaims are the
 * expensive kind -- they are the ones that survive to an interview.
 */
const IMPLEMENTED_EQUIVALENT = {
  tone: 'ok' as Tone,
  label: 'IMPLEMENTED (software equivalent)',
  detail: 'Real, tested code in this project, on a different platform than the stage name implies',
}

const STAGES: Stage[] = [
  {
    name: 'Physical Asset',
    role: 'MTR-101 motor driving P-101 centrifugal pump',
    detail:
      'A single-stage end-suction pump on a 4-pole induction motor, ' +
      `${PUMP.duty_flow_lpm} L/min at ${PUMP.duty_head_m} m head. No physical machine exists: ` +
      'its behaviour is generated by the pump and motor equations.',
    status: SIMULATED,
  },
  {
    name: 'Sensors',
    role: 'ACC-101, TT-101, TT-102, PT-101, PT-102, FT-101, CT-101, RPM-101',
    detail:
      'Accelerometer, two RTDs, two pressure transmitters, a flow meter, a current transformer and a speed pickup. Each carries a quality flag (GOOD / UNCERTAIN / BAD) so a suspect channel can be distinguished from a genuine process change.',
    status: SIMULATED,
  },
  {
    name: 'DAQ / Edge',
    role: 'Sampling, scaling, quality tagging',
    detail:
      'Converts raw sensor signals into engineering units at a fixed tick rate and attaches provenance. In this project the tick is 0.5 s for process values, with the vibration waveform sampled far faster for spectral analysis.',
    status: SIMULATED,
  },
  {
    name: 'PLC',
    role: 'Control state machine and interlocks',
    detail:
      'OFF / STARTING / RUNNING / STOPPING / FAULT / E_STOP / MAINTENANCE with the transitions and refusals shown on the SCADA page. Protection trips act on the same limits the alarm list displays. The logic is real and tested; what runs it is a Python state machine, not ladder or structured text on PLC hardware, so no scan-cycle timing, no I/O module behaviour and no fail-safe output state is being demonstrated here.',
    status: IMPLEMENTED_EQUIVALENT,
  },
  {
    name: 'Acquisition',
    role: 'FastAPI REST + websocket transport',
    detail:
      'REST endpoints for status, sensors, diagnosis, alarms, history, pump curve, vibration and FFT; a websocket streaming one Telemetry frame per tick. Field names are frozen by backend/app/contracts.py and mirrored verbatim into the React types.',
    status: IMPLEMENTED,
  },
  {
    name: 'Signal Processing',
    role: 'RMS, peak, crest factor, FFT, band energy',
    detail:
      'Velocity waveform statistics and the magnitude spectrum, with the synchronous orders (1x, 2x) and blade-pass frequency extracted. Bearing defect frequencies are computed kinematically from geometry.',
    status: IMPLEMENTED,
  },
  {
    name: 'Physics Model',
    role: 'Pump curve, system curve, operating point, NPSH',
    detail:
      'Flow is solved as the intersection of the two quadratic characteristics; head, efficiency, hydraulic, shaft and electrical power and the NPSH margin all follow from it. Nothing downstream invents a coefficient.',
    status: IMPLEMENTED,
  },
  {
    name: 'Machine Learning',
    role: 'Fault classification and anomaly detection',
    detail:
      'A supervised classifier over the 16-feature contract vector predicts the condition; an unsupervised detector scores novelty. The feature order is frozen in the contract, because a model trained on one order and served with another produces confident nonsense and raises no error.',
    status: IMPLEMENTED,
  },
  {
    name: 'Digital Twin',
    role: 'Geometric and behavioural twin',
    detail:
      'A 3D model whose shaft speed tracks the measured rpm, whose sensor markers carry live readings with quality and limits, and whose visual shake is an exaggerated indication of vibration rather than true displacement.',
    status: IMPLEMENTED,
  },
  {
    name: 'Maintenance Decision',
    role: 'Condition, evidence, recommended action, work order',
    detail:
      'Physics evidence and model evidence are presented separately so the reasoning can be challenged, with feature importances and recommended actions. The generated work order is explicitly a demonstration artefact.',
    status: IMPLEMENTED,
  },
]

export function Architecture() {
  return (
    <div className="space-y-5">
      <PageHeading
        title="Architecture"
        description="From physical asset to maintenance decision. Each stage states whether it is implemented in this project or simulated in place of hardware."
      />

      <Card title="Pipeline">
        <ol className="space-y-0">
          {STAGES.map((stage, index) => (
            <li key={stage.name}>
              <div className="flex flex-col gap-3 rounded-lg border border-slate-200 p-4 sm:flex-row sm:items-start">
                <div className="flex shrink-0 items-center gap-3 sm:w-64">
                  <span className="numeric flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-slate-900 text-xs font-bold text-white">
                    {index + 1}
                  </span>
                  <div className="min-w-0">
                    <p className="text-sm font-semibold text-slate-900">{stage.name}</p>
                    <p className="mt-0.5 text-xs text-slate-500">{stage.role}</p>
                  </div>
                </div>
                <p className="min-w-0 flex-1 text-sm text-slate-600">{stage.detail}</p>
                <div className="shrink-0">
                  <StatusBadge status={stage.status} size="sm" />
                </div>
              </div>
              {index < STAGES.length - 1 && (
                <div className="flex justify-center py-1.5 text-slate-400">
                  <ArrowDown className="h-4 w-4" aria-hidden />
                  <span className="sr-only">feeds into</span>
                </div>
              )}
            </li>
          ))}
        </ol>
      </Card>

      <Card title="Data contract" subtitle="Why the field names never change">
        <p className="text-sm leading-relaxed text-slate-600">
          One module defines the field names on the wire, in storage and in the React types:{' '}
          <code className="numeric rounded bg-slate-100 px-1.5 py-0.5 text-xs">
            backend/app/contracts.py
          </code>
          . The frontend mirrors it verbatim in{' '}
          <code className="numeric rounded bg-slate-100 px-1.5 py-0.5 text-xs">
            src/types/contracts.ts
          </code>{' '}
          -- no camelCase conversion, no renaming, no nesting.
        </p>
        <p className="mt-3 text-sm leading-relaxed text-slate-600">
          The reason is a specific failure mode rather than a style preference. If a producer writes{' '}
          <code className="numeric text-xs">flow_lpm</code> and a consumer reads{' '}
          <code className="numeric text-xs">flowRate</code>, the consumer gets{' '}
          <code className="numeric text-xs">undefined</code>, the chart draws an empty line, and
          nothing anywhere raises an error. Silent contract drift is far more expensive to find than
          a crash.
        </p>
      </Card>

      <Card title="Frontend structure">
        <div className="grid gap-4 text-sm sm:grid-cols-2">
          <div>
            <p className="font-semibold text-slate-900">Transport and state</p>
            <ul className="mt-2 space-y-1.5 text-slate-600">
              <li className="flex gap-2">
                <ArrowRight className="mt-0.5 h-3.5 w-3.5 shrink-0 text-slate-400" aria-hidden />
                A single websocket in one provider feeds every page, so navigating does not tear the
                stream down.
              </li>
              <li className="flex gap-2">
                <ArrowRight className="mt-0.5 h-3.5 w-3.5 shrink-0 text-slate-400" aria-hidden />
                Reconnection uses exponential backoff with jitter, capped at 20 seconds.
              </li>
              <li className="flex gap-2">
                <ArrowRight className="mt-0.5 h-3.5 w-3.5 shrink-0 text-slate-400" aria-hidden />
                REST calls never throw at the UI: they resolve to the payload or to null.
              </li>
            </ul>
          </div>
          <div>
            <p className="font-semibold text-slate-900">Degradation</p>
            <ul className="mt-2 space-y-1.5 text-slate-600">
              <li className="flex gap-2">
                <ArrowRight className="mt-0.5 h-3.5 w-3.5 shrink-0 text-slate-400" aria-hidden />
                With no backend, a bundled recorded dataset replays and is labelled as such.
              </li>
              <li className="flex gap-2">
                <ArrowRight className="mt-0.5 h-3.5 w-3.5 shrink-0 text-slate-400" aria-hidden />
                Using any control offline hands over to a browser-side plant model, so the SCADA and
                Simulation pages stay demonstrable.
              </li>
              <li className="flex gap-2">
                <ArrowRight className="mt-0.5 h-3.5 w-3.5 shrink-0 text-slate-400" aria-hidden />
                Every page and every chart sits inside an error boundary, so one broken panel cannot
                blank the page.
              </li>
            </ul>
          </div>
        </div>
      </Card>

      <ProvenanceNote>
        This is an engineering portfolio prototype. The asset, its sensors and all of its data are
        simulated. Nothing in this system has been connected to real plant, and it is not a
        certified condition-monitoring product.
      </ProvenanceNote>
    </div>
  )
}
